"""Main configuration file for CNN visualization training."""

defaults:
  - model: simple_cnn
  - data: cifar10
  - trainer: default
  - _self_

# Model configuration
model:
  num_classes: 10
  learning_rate: 1e-3
  pretrained: true

# Data configuration
data:
  data_dir: ./data
  batch_size: 32
  num_workers: 4
  normalize: true

# Trainer configuration
trainer:
  max_epochs: 10
  accelerator: auto
  devices: auto
  precision: 32

# Logging
log_dir: ./logs
experiment_name: cnn_visualization
seed: 42